// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.DATA;

#nullable disable

namespace NZwalks.API.Migrations
{
    [DbContext(typeof(NZWalksDBContext))]
    [Migration("20260731235316_SeedDifficultiesAndRegions")]
    partial class SeedDifficultiesAndRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.MODELS.DOMAIN.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e9d5ab1-e4a1-4a7d-8f0a-74a2bfa6c101"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("2c6e41b0-8b7d-4fdf-8dfb-8a4c5ee3d102"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("f3a7c868-2d66-45a0-a6c7-26c8be20a103"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.MODELS.DOMAIN.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0e19e8d-9ca6-4e64-93d8-4aafa1bf9101"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://images.unsplash.com/photo-1507699622108-4be3abd695ad"
                        },
                        new
                        {
                            Id = new Guid("f9da6c03-ad3e-4b53-af7e-4ae0c7d59102"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e"
                        },
                        new
                        {
                            Id = new Guid("a6f7b710-81b1-47fc-8665-9c715fbf9103"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://images.unsplash.com/photo-1472396961693-142e6e269027"
                        },
                        new
                        {
                            Id = new Guid("8c1fbea1-8b9d-43e9-8a0f-b8d7411c9104"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://images.unsplash.com/photo-1516298773066-c48f8e9bd92b"
                        },
                        new
                        {
                            Id = new Guid("0d0f1a74-d457-4f55-9c5c-4c0ee28c9105"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://images.unsplash.com/photo-1470770841072-f978cf4d019e"
                        },
                        new
                        {
                            Id = new Guid("b23d4f8c-785a-4f19-a6f5-915ea2bc9106"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageUrl = "https://images.unsplash.com/photo-1441974231531-c6227db76b6e"
                        });
                });

            modelBuilder.Entity("NZWalks.API.MODELS.DOMAIN.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LengthInKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.MODELS.DOMAIN.Walks", b =>
                {
                    b.HasOne("NZWalks.API.MODELS.DOMAIN.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.MODELS.DOMAIN.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
